import { PrismaClient, Prisma } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding database…')

  // Clear existing seed data (by normalized name pattern or just wipe for dev)
  await prisma.signal.deleteMany()
  await prisma.contact.deleteMany()
  await prisma.companyTag.deleteMany()
  await prisma.userNote.deleteMany()
  await prisma.company.deleteMany()
  await prisma.crawlJob.deleteMany()

  // ─── Companies ─────────────────────────────────────────────────────────────
  // Distribution target:
  //   6+ industrial, 6+ commercial, 6+ residential, 6+ mixed
  //   Counties: Gwinnett, Hall, Forsyth, Cobb, Fulton, Cherokee

  const companies = await Promise.all([

    // ── INDUSTRIAL (6) ───────────────────────────────────────────────────────
    prisma.company.create({ data: {
      name: 'Piedmont Industrial Electric',
      normalizedName: 'piedmont industrial electric',
      website: 'https://piedmontindustrialelectric.com',
      domain: 'piedmontindustrialelectric.com',
      phone: '7706221100',
      email: 'service@piedmontindustrialelectric.com',
      street: '4250 Industrial Blvd',
      city: 'Buford',
      state: 'GA',
      zip: '30518',
      county: 'Gwinnett',
      region: 'Northeast Atlanta Metro',
      territory: 'Gwinnett/Hall',
      segments: ['industrial'],
      specialties: ['switchgear', 'panelboards', 'motor controls', 'industrial maintenance'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.9,
      activeScore: 85,
      leadScore: 88,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Gainesville Power Solutions',
      normalizedName: 'gainesville power solutions',
      website: 'https://gainesvillepowersolutions.com',
      domain: 'gainesvillepowersolutions.com',
      phone: '7704321800',
      email: 'info@gainesvillepowersolutions.com',
      street: '801 Green St NW',
      city: 'Gainesville',
      state: 'GA',
      zip: '30501',
      county: 'Hall',
      region: 'North Georgia',
      territory: 'Hall/Forsyth',
      segments: ['industrial'],
      specialties: ['generators', 'switchgear', 'controls', 'distribution center'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.85,
      activeScore: 78,
      leadScore: 82,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Cherokee Automation & Electric',
      normalizedName: 'cherokee automation electric',
      website: null,
      domain: null,
      phone: '6782551450',
      email: null,
      street: '215 Waleska Rd',
      city: 'Canton',
      state: 'GA',
      zip: '30114',
      county: 'Cherokee',
      region: 'North Atlanta Metro',
      territory: 'Cherokee/Cobb',
      segments: ['industrial'],
      specialties: ['controls', 'motor controls', 'industrial maintenance', 'low voltage'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.7,
      activeScore: 55,
      leadScore: 65,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Forsyth County Electric Service',
      normalizedName: 'forsyth county electric service',
      website: 'https://forsythelectricservice.net',
      domain: 'forsythelectricservice.net',
      phone: '7706450990',
      email: 'billing@forsythelectricservice.net',
      street: '5100 Commerce Pkwy',
      city: 'Cumming',
      state: 'GA',
      zip: '30028',
      county: 'Forsyth',
      region: 'North Atlanta Metro',
      territory: 'Forsyth/Cherokee',
      segments: ['industrial'],
      specialties: ['panelboards', 'switchgear', 'warehouse', 'EV charging'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.8,
      activeScore: 72,
      leadScore: 79,
      status: 'QUALIFYING',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Metro Atlanta Industrial Contractors',
      normalizedName: 'metro atlanta industrial contractors',
      website: 'https://maic.electrical.com',
      domain: 'maic.electrical.com',
      phone: '6788820055',
      email: 'projects@maicelectrical.com',
      street: '3900 Oakcliff Industrial Ct',
      city: 'Atlanta',
      state: 'GA',
      zip: '30340',
      county: 'Fulton',
      region: 'Atlanta Core',
      territory: 'Fulton/DeKalb',
      segments: ['industrial'],
      specialties: ['switchgear', 'panelboards', 'controls', 'generators', 'healthcare'],
      employeeSizeEstimate: '51-200',
      sourceConfidence: 0.92,
      activeScore: 90,
      leadScore: 92,
      status: 'QUALIFYING',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'North Georgia Wire & Controls',
      normalizedName: 'north georgia wire controls',
      website: null,
      domain: null,
      phone: '7704192275',
      email: 'ngwc@outlook.com',
      street: '1012 Industrial Dr',
      city: 'Oakwood',
      state: 'GA',
      zip: '30566',
      county: 'Hall',
      region: 'North Georgia',
      territory: 'Hall/Forsyth',
      segments: ['industrial'],
      specialties: ['motor controls', 'controls', 'industrial maintenance'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.65,
      activeScore: 45,
      leadScore: 55,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    // ── COMMERCIAL (6) ───────────────────────────────────────────────────────
    prisma.company.create({ data: {
      name: 'Suwanee Commercial Electric',
      normalizedName: 'suwanee commercial electric',
      website: 'https://suwaneecommercialelectric.com',
      domain: 'suwaneecommercialelectric.com',
      phone: '7709451200',
      email: 'info@suwaneecommercialelectric.com',
      street: '3780 Satellite Blvd',
      city: 'Suwanee',
      state: 'GA',
      zip: '30024',
      county: 'Gwinnett',
      region: 'Northeast Atlanta Metro',
      territory: 'Gwinnett/Hall',
      segments: ['commercial'],
      specialties: ['tenant improvement', 'lighting', 'low voltage', 'fire alarm'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.88,
      activeScore: 74,
      leadScore: 76,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Marietta Office & Retail Electric',
      normalizedName: 'marietta office retail electric',
      website: 'https://mariettaelectricpro.com',
      domain: 'mariettaelectricpro.com',
      phone: '7706273000',
      email: 'estimate@mariettaelectricpro.com',
      street: '680 Whitlock Ave NW',
      city: 'Marietta',
      state: 'GA',
      zip: '30064',
      county: 'Cobb',
      region: 'Northwest Atlanta Metro',
      territory: 'Cobb/Cherokee',
      segments: ['commercial'],
      specialties: ['tenant improvement', 'lighting', 'EV charging', 'schools'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.82,
      activeScore: 68,
      leadScore: 71,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Cumming Commercial Electrical',
      normalizedName: 'cumming commercial electrical',
      website: 'https://cummingcommercialelectric.net',
      domain: 'cummingcommercialelectric.net',
      phone: '6782889400',
      email: null,
      street: '2200 Market Place Blvd',
      city: 'Cumming',
      state: 'GA',
      zip: '30041',
      county: 'Forsyth',
      region: 'North Atlanta Metro',
      territory: 'Forsyth/Cherokee',
      segments: ['commercial'],
      specialties: ['tenant improvement', 'fire alarm', 'low voltage', 'lighting'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.72,
      activeScore: 58,
      leadScore: 60,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Buckhead Electrical Systems',
      normalizedName: 'buckhead electrical systems',
      website: 'https://buckheadelectrical.com',
      domain: 'buckheadelectrical.com',
      phone: '4042551900',
      email: 'info@buckheadelectrical.com',
      street: '3390 Peachtree Rd NE',
      city: 'Atlanta',
      state: 'GA',
      zip: '30326',
      county: 'Fulton',
      region: 'Atlanta Core',
      territory: 'Fulton/DeKalb',
      segments: ['commercial'],
      specialties: ['healthcare', 'tenant improvement', 'lighting', 'low voltage'],
      employeeSizeEstimate: '51-200',
      sourceConfidence: 0.91,
      activeScore: 82,
      leadScore: 84,
      status: 'QUALIFYING',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Canton Business Electric',
      normalizedName: 'canton business electric',
      website: null,
      domain: null,
      phone: '7706891700',
      email: 'cantonbizelectric@gmail.com',
      street: '1540 Marietta Hwy',
      city: 'Canton',
      state: 'GA',
      zip: '30115',
      county: 'Cherokee',
      region: 'North Atlanta Metro',
      territory: 'Cherokee/Cobb',
      segments: ['commercial'],
      specialties: ['tenant improvement', 'service'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.6,
      activeScore: 38,
      leadScore: 42,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Kennesaw Commercial Contracting Electric',
      normalizedName: 'kennesaw commercial contracting electric',
      website: 'https://kennesawcommercialelec.com',
      domain: 'kennesawcommercialelec.com',
      phone: '7705148822',
      email: 'sales@kennesawcommercialelec.com',
      street: '900 Roberts Ct NW',
      city: 'Kennesaw',
      state: 'GA',
      zip: '30144',
      county: 'Cobb',
      region: 'Northwest Atlanta Metro',
      territory: 'Cobb/Cherokee',
      segments: ['commercial'],
      specialties: ['schools', 'municipal', 'lighting', 'low voltage', 'fire alarm'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.84,
      activeScore: 70,
      leadScore: 73,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    // ── RESIDENTIAL (6) ──────────────────────────────────────────────────────
    prisma.company.create({ data: {
      name: 'Duluth Residential Wiring',
      normalizedName: 'duluth residential wiring',
      website: 'https://duluthresidentialwiring.com',
      domain: 'duluthresidentialwiring.com',
      phone: '6787001180',
      email: 'service@duluthresidentialwiring.com',
      street: '2050 Pleasant Hill Rd',
      city: 'Duluth',
      state: 'GA',
      zip: '30096',
      county: 'Gwinnett',
      region: 'Northeast Atlanta Metro',
      territory: 'Gwinnett/Hall',
      segments: ['residential'],
      specialties: ['service', 'panel upgrade', 'multifamily'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.75,
      activeScore: 35,
      leadScore: 30,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Alpharetta Home Electric',
      normalizedName: 'alpharetta home electric',
      website: 'https://alpharettahomeelectric.com',
      domain: 'alpharettahomeelectric.com',
      phone: '7706643300',
      email: 'info@alpharettahomeelectric.com',
      street: '4020 Windward Plaza Dr',
      city: 'Alpharetta',
      state: 'GA',
      zip: '30005',
      county: 'Forsyth',
      region: 'North Atlanta Metro',
      territory: 'Forsyth/Cherokee',
      segments: ['residential'],
      specialties: ['service', 'EV charging', 'panel upgrade'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.7,
      activeScore: 30,
      leadScore: 28,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Smyrna Home & Garden Electric',
      normalizedName: 'smyrna home garden electric',
      website: null,
      domain: null,
      phone: '7708019900',
      email: 'smyrnahomeelectric@yahoo.com',
      street: '2800 Atlanta Rd SE',
      city: 'Smyrna',
      state: 'GA',
      zip: '30080',
      county: 'Cobb',
      region: 'Northwest Atlanta Metro',
      territory: 'Cobb/Cherokee',
      segments: ['residential'],
      specialties: ['service', 'panel upgrade'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.55,
      activeScore: 22,
      leadScore: 20,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Ball Ground Home Electrical',
      normalizedName: 'ball ground home electrical',
      website: null,
      domain: null,
      phone: '7706340088',
      email: null,
      street: '310 Gilmer Ferry Rd',
      city: 'Ball Ground',
      state: 'GA',
      zip: '30107',
      county: 'Cherokee',
      region: 'North Atlanta Metro',
      territory: 'Cherokee/Cobb',
      segments: ['residential'],
      specialties: ['service'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.5,
      activeScore: 15,
      leadScore: 14,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Inman Park Residential Electrical',
      normalizedName: 'inman park residential electrical',
      website: 'https://inmanparkelectric.com',
      domain: 'inmanparkelectric.com',
      phone: '4042200550',
      email: 'book@inmanparkelectric.com',
      street: '240 DeKalb Ave NE',
      city: 'Atlanta',
      state: 'GA',
      zip: '30307',
      county: 'Fulton',
      region: 'Atlanta Core',
      territory: 'Fulton/DeKalb',
      segments: ['residential'],
      specialties: ['service', 'panel upgrade', 'multifamily', 'EV charging'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.72,
      activeScore: 32,
      leadScore: 29,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Flowery Branch Home Electric',
      normalizedName: 'flowery branch home electric',
      website: 'https://flowerybranchelectric.com',
      domain: 'flowerybranchelectric.com',
      phone: '7704991300',
      email: 'fbhomeelectric@gmail.com',
      street: '4500 Thurmon Tanner Pkwy',
      city: 'Flowery Branch',
      state: 'GA',
      zip: '30542',
      county: 'Hall',
      region: 'North Georgia',
      territory: 'Hall/Forsyth',
      segments: ['residential'],
      specialties: ['service', 'panel upgrade'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.65,
      activeScore: 28,
      leadScore: 26,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    // ── MIXED / OVERLAP (6) ──────────────────────────────────────────────────
    prisma.company.create({ data: {
      name: 'Lawrenceville Full Service Electric',
      normalizedName: 'lawrenceville full service electric',
      website: 'https://lawrencevilleelectric.com',
      domain: 'lawrencevilleelectric.com',
      phone: '7705131900',
      email: 'dispatch@lawrencevilleelectric.com',
      street: '770 Hurricane Shoals Rd NE',
      city: 'Lawrenceville',
      state: 'GA',
      zip: '30046',
      county: 'Gwinnett',
      region: 'Northeast Atlanta Metro',
      territory: 'Gwinnett/Hall',
      segments: ['commercial', 'residential', 'industrial'],
      specialties: ['service', 'tenant improvement', 'panelboards', 'lighting', 'generators'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.86,
      activeScore: 76,
      leadScore: 80,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Lula All-Trade Electrical',
      normalizedName: 'lula all-trade electrical',
      website: null,
      domain: null,
      phone: '7706773120',
      email: 'lulaelectric@gmail.com',
      street: '5230 Cornelia Hwy',
      city: 'Lula',
      state: 'GA',
      zip: '30554',
      county: 'Hall',
      region: 'North Georgia',
      territory: 'Hall/Forsyth',
      segments: ['commercial', 'residential'],
      specialties: ['service', 'panel upgrade', 'fire alarm', 'lighting'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.62,
      activeScore: 42,
      leadScore: 45,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Powers Ferry Electrical Group',
      normalizedName: 'powers ferry electrical group',
      website: 'https://powersferry.electric',
      domain: 'powersferry.electric',
      phone: '7703880400',
      email: 'contracts@powersferry.electric',
      street: '1600 Powers Ferry Rd SE',
      city: 'Marietta',
      state: 'GA',
      zip: '30067',
      county: 'Cobb',
      region: 'Northwest Atlanta Metro',
      territory: 'Cobb/Cherokee',
      segments: ['industrial', 'commercial'],
      specialties: ['switchgear', 'controls', 'healthcare', 'low voltage', 'fire alarm'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.88,
      activeScore: 80,
      leadScore: 83,
      status: 'QUALIFYING',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Midtown Commercial & Industrial Electric',
      normalizedName: 'midtown commercial industrial electric',
      website: 'https://midtowncie.com',
      domain: 'midtowncie.com',
      phone: '4045003300',
      email: 'ops@midtowncie.com',
      street: '887 Spring St NW',
      city: 'Atlanta',
      state: 'GA',
      zip: '30308',
      county: 'Fulton',
      region: 'Atlanta Core',
      territory: 'Fulton/DeKalb',
      segments: ['commercial', 'industrial'],
      specialties: ['switchgear', 'tenant improvement', 'EV charging', 'panelboards', 'lighting'],
      employeeSizeEstimate: '51-200',
      sourceConfidence: 0.93,
      activeScore: 88,
      leadScore: 90,
      status: 'QUALIFYING',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Roswell Tri-Trade Electric',
      normalizedName: 'roswell tri-trade electric',
      website: 'https://roswelltritrade.com',
      domain: 'roswelltritrade.com',
      phone: '7703602200',
      email: 'office@roswelltritrade.com',
      street: '4510 Shallowford Rd',
      city: 'Roswell',
      state: 'GA',
      zip: '30075',
      county: 'Fulton',
      region: 'North Atlanta Metro',
      territory: 'Forsyth/Cherokee',
      segments: ['commercial', 'residential', 'industrial'],
      specialties: ['service', 'tenant improvement', 'controls', 'multifamily', 'lighting'],
      employeeSizeEstimate: '11-50',
      sourceConfidence: 0.81,
      activeScore: 65,
      leadScore: 68,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),

    prisma.company.create({ data: {
      name: 'Woodstock Mixed-Use Electric',
      normalizedName: 'woodstock mixed-use electric',
      website: null,
      domain: null,
      phone: '6786881600',
      email: 'woodstockelec@outlook.com',
      street: '210 N Main St',
      city: 'Woodstock',
      state: 'GA',
      zip: '30188',
      county: 'Cherokee',
      region: 'North Atlanta Metro',
      territory: 'Cherokee/Cobb',
      segments: ['commercial', 'residential'],
      specialties: ['service', 'lighting', 'panel upgrade', 'tenant improvement'],
      employeeSizeEstimate: '1-10',
      sourceConfidence: 0.67,
      activeScore: 48,
      leadScore: 50,
      status: 'NEW',
      doNotContact: false,
      recordOrigin: 'DEMO',
    }}),
  ])

  console.log(`Created ${companies.length} companies`)

  // ─── Signals ────────────────────────────────────────────────────────────────
  // At least half the companies get 2-4 signals with varied source types
  const signalData: Prisma.SignalCreateManyInput[] = [
    // Piedmont Industrial Electric
    { companyId: companies[0].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Industrial MCC Work Highlighted', snippet: 'Specializes in motor control centers, 480V distribution, and factory automation wiring for manufacturing plants across Gwinnett and Hall counties.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-11-15'), county: 'Gwinnett', relevanceScore: 0.92 },
    { companyId: companies[0].id, sourceType: 'PERMIT' as const, sourceName: 'Gwinnett County Permits', title: 'Commercial/Industrial Permit Filed', snippet: 'Electrical permit for new 400A service and switchgear installation at Buford industrial facility.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-01'), county: 'Gwinnett', relevanceScore: 0.88 },
    { companyId: companies[0].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Generator and Emergency Power Division', snippet: 'Offers generator installation, transfer switches, and UPS systems for industrial clients requiring 24/7 uptime.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-20'), county: 'Gwinnett', relevanceScore: 0.85 },
    // Gainesville Power Solutions
    { companyId: companies[1].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Distribution Center Electrical Work', snippet: 'Completed switchgear and feeder installation for a 200,000 sq ft distribution center in Hall County.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-09-30'), county: 'Hall', relevanceScore: 0.89 },
    { companyId: companies[1].id, sourceType: 'PERMIT' as const, sourceName: 'Hall County Permits', title: 'Industrial Switchgear Permit', snippet: 'Permit for 2000A switchboard replacement at manufacturing site, Hall County.', signalType: 'PERMIT' as const, signalDate: new Date('2024-11-05'), county: 'Hall', relevanceScore: 0.91 },
    // Forsyth County Electric Service
    { companyId: companies[3].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'EV Charging Installations for Fleet', snippet: 'Now offering Level 2 and DC fast charger installation for commercial fleet operators across Forsyth County.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-12'), county: 'Forsyth', relevanceScore: 0.87 },
    { companyId: companies[3].id, sourceType: 'LICENSE' as const, sourceName: 'GA SOS Licensing', title: 'EC License Renewal', snippet: 'Electrical contractor license renewed — EC001234 valid through 2026.', signalType: 'LICENSE' as const, signalDate: new Date('2024-08-01'), county: 'Forsyth', relevanceScore: 0.7 },
    // Metro Atlanta Industrial
    { companyId: companies[4].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Healthcare and Industrial Portfolio', snippet: 'Multi-million dollar electrical infrastructure for hospitals, data centers, and heavy manufacturing plants in metro Atlanta.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-12-10'), county: 'Fulton', relevanceScore: 0.95 },
    { companyId: companies[4].id, sourceType: 'PERMIT' as const, sourceName: 'Fulton County Permits', title: 'High-Voltage Permit — Healthcare', snippet: '4160V primary distribution work permitted for hospital expansion, Fulton County.', signalType: 'PERMIT' as const, signalDate: new Date('2024-11-20'), county: 'Fulton', relevanceScore: 0.93 },
    { companyId: companies[4].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Generator Fleet Management', snippet: 'Maintains emergency generator systems across 12 healthcare facilities in metro Atlanta.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-05'), county: 'Fulton', relevanceScore: 0.88 },
    // Suwanee Commercial Electric
    { companyId: companies[6].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Retail & Office Tenant Improvement', snippet: 'Specializes in TI work for retail buildouts and Class A office space in Gwinnett County.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-11-08'), county: 'Gwinnett', relevanceScore: 0.82 },
    { companyId: companies[6].id, sourceType: 'PERMIT' as const, sourceName: 'Gwinnett County Permits', title: 'Commercial Lighting Upgrade', snippet: 'LED retrofit permit for 35,000 sq ft retail center, Suwanee.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-03'), county: 'Gwinnett', relevanceScore: 0.79 },
    // Buckhead Electrical Systems
    { companyId: companies[9].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Healthcare Electrical Division', snippet: 'Dedicated healthcare team handles NFPA 99-compliant installations for Fulton County medical facilities.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-09-15'), county: 'Fulton', relevanceScore: 0.91 },
    { companyId: companies[9].id, sourceType: 'PERMIT' as const, sourceName: 'Fulton County Permits', title: 'Medical Office Build-Out', snippet: 'Electrical permit for 8,000 sq ft specialist clinic, Buckhead.', signalType: 'PERMIT' as const, signalDate: new Date('2024-11-30'), county: 'Fulton', relevanceScore: 0.86 },
    { companyId: companies[9].id, sourceType: 'LICENSE' as const, sourceName: 'GA SOS Licensing', title: 'Unrestricted EC License', snippet: 'Unrestricted electrical contractor license EC009871 active, Fulton County.', signalType: 'LICENSE' as const, signalDate: new Date('2024-07-01'), county: 'Fulton', relevanceScore: 0.72 },
    // Lawrenceville Full Service
    { companyId: companies[12].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Multi-Trade Capabilities', snippet: 'Industrial, commercial, and residential electrical serving Gwinnett and surrounding counties since 2004.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-25'), county: 'Gwinnett', relevanceScore: 0.83 },
    { companyId: companies[12].id, sourceType: 'PERMIT' as const, sourceName: 'Gwinnett County Permits', title: 'Generator and Panel Permit', snippet: 'Combined permit: 200kW generator + 800A service upgrade, industrial facility, Lawrenceville.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-05'), county: 'Gwinnett', relevanceScore: 0.87 },
    // Powers Ferry Electrical Group
    { companyId: companies[14].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Switchgear and Controls Specialists', snippet: 'Design-build electrical for healthcare campuses, data centers, and heavy industrial with switchgear up to 15kV.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-11-01'), county: 'Cobb', relevanceScore: 0.93 },
    { companyId: companies[14].id, sourceType: 'PERMIT' as const, sourceName: 'Cobb County Permits', title: 'Healthcare Switchgear Replacement', snippet: 'Emergency switchgear replacement permitted, Cobb County hospital, 2400A service.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-08'), county: 'Cobb', relevanceScore: 0.90 },
    { companyId: companies[14].id, sourceType: 'LICENSE' as const, sourceName: 'GA SOS Licensing', title: 'Active EC License', snippet: 'EC license EC005512 active, Cobb County master electrician on staff.', signalType: 'LICENSE' as const, signalDate: new Date('2024-06-15'), county: 'Cobb', relevanceScore: 0.68 },
    // Midtown Commercial & Industrial
    { companyId: companies[15].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Mixed-Use High Rise Electrical', snippet: 'Ground-up electrical for mixed-use towers in Midtown Atlanta — commercial podium and residential tower service.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-18'), county: 'Fulton', relevanceScore: 0.94 },
    { companyId: companies[15].id, sourceType: 'PERMIT' as const, sourceName: 'Fulton County Permits', title: 'EV Charging Infrastructure Permit', snippet: 'Level 2 charging infrastructure permit, 48-port commercial garage, Midtown Atlanta.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-12'), county: 'Fulton', relevanceScore: 0.91 },
    { companyId: companies[15].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Panelboard and Switchgear Division', snippet: 'Specializes in 480V/208V distribution design for commercial high rises and industrial campuses.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-09-20'), county: 'Fulton', relevanceScore: 0.89 },
    // Kennesaw Commercial
    { companyId: companies[11].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Schools and Municipal Projects', snippet: 'Electrical contracting for K-12 schools, public works, and county facilities in Cobb County.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-11-25'), county: 'Cobb', relevanceScore: 0.84 },
    { companyId: companies[11].id, sourceType: 'PERMIT' as const, sourceName: 'Cobb County Permits', title: 'School Renovation Permit', snippet: 'Electrical permit for renovation of elementary school gym and cafeteria, Kennesaw.', signalType: 'PERMIT' as const, signalDate: new Date('2024-12-01'), county: 'Cobb', relevanceScore: 0.81 },
    // Roswell Tri-Trade
    { companyId: companies[16].id, sourceType: 'COMPANY_WEBSITE' as const, sourceName: 'Company website', title: 'Multifamily and Commercial Portfolio', snippet: 'Built over 2,000 residential units and 500,000 sq ft of commercial space in North Atlanta since 2010.', signalType: 'WEBSITE_CONTENT' as const, signalDate: new Date('2024-10-30'), county: 'Fulton', relevanceScore: 0.80 },
    { companyId: companies[16].id, sourceType: 'PERMIT' as const, sourceName: 'Fulton County Permits', title: 'Multifamily New Construction', snippet: '240-unit apartment complex electrical permit, Roswell.', signalType: 'PERMIT' as const, signalDate: new Date('2024-11-15'), county: 'Fulton', relevanceScore: 0.78 },
  ]

  const signals = await prisma.signal.createMany({ data: signalData })
  console.log(`Created ${signals.count} signals`)

  // ─── Contacts ───────────────────────────────────────────────────────────────
  const contacts = await prisma.contact.createMany({
    data: [
      { companyId: companies[0].id, name: 'Gary Tillman', title: 'Owner', email: 'gtillman@piedmontindustrialelectric.com', phone: '7706221101', source: 'website', confidenceScore: 0.85 },
      { companyId: companies[4].id, name: 'Angela Simmons', title: 'VP Operations', email: 'asimmons@maicelectrical.com', phone: '6788820056', source: 'website', confidenceScore: 0.9 },
      { companyId: companies[9].id, name: 'Derek Worthington', title: 'Project Manager', email: 'dworthington@buckheadelectrical.com', phone: '4042551901', source: 'website', confidenceScore: 0.87 },
      { companyId: companies[14].id, name: 'Sandra Mejia', title: 'Estimating Lead', email: 'smejia@powersferry.electric', phone: '7703880401', source: 'website', confidenceScore: 0.82 },
      { companyId: companies[15].id, name: 'James Okonkwo', title: 'President', email: 'jokonkwo@midtowncie.com', phone: '4045003301', source: 'website', confidenceScore: 0.91 },
      { companyId: companies[6].id, name: 'Rachel Patel', title: 'Office Manager', email: 'rpatel@suwaneecommercialelectric.com', phone: '7709451201', source: 'website', confidenceScore: 0.78 },
    ],
  })
  console.log(`Created ${contacts.count} contacts`)

  // ─── Sample CrawlJob ────────────────────────────────────────────────────────
  await prisma.crawlJob.create({
    data: {
      sourceType: 'COMPANY_WEBSITE',
      status: 'COMPLETED',
      startedAt: new Date('2024-12-15T10:00:00Z'),
      finishedAt: new Date('2024-12-15T10:04:32Z'),
      recordsFound: 5,
      recordsCreated: 0,
      recordsUpdated: 5,
      metadata: { note: 'Seed demo crawl job' },
    },
  })

  console.log('Seed complete.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
